### PR TITLE
Improvements to Marker component

### PR DESCRIPTION
**Pull request by gneutzling**
We are using react-maps and arose the necessity of listen the drag events to the marker. Then we created events listeners to the component.

Thanks for help @edmargomes

Regards.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Hey @gneutzling, thanks for your contribution.

The idea to improve the `Marker` component is very good, I just see some problems in your code:

- modified the code in the `dist` folder (will be overwritten during the build process)
- added `Map` events to the `Marker` (which has [his own events](https://developers.google.com/maps/documentation/javascript/reference#Marker))
- duplicated the code to listen to events (it would be nice to use a [Mixin](https://facebook.github.io/react/docs/reusable-components.html#mixins) instead)

Are you happy to fix your PR or do you prefer me to add this functionality?

**Comment by gneutzling** [comment]
Sorry for the delay @MicheleBertoli .. 

I am busy working in another project, but I would like to help you with react-gmaps. Maybe we can work in these new features and improvements together, what do you think?

And... Yeap! Today I saw this PR and I think we can do much better :P

**Comment by MicheleBertoli** [comment]
Hey @gneutzling, I will be happy to work with you :)

Mainly, our tasks are:
- [ ] add `MarkerEvents` to [Events](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/events.js) (details [here](https://developers.google.com/maps/documentation/javascript/reference#Marker)).
- [ ] extract `bindEvents` and `unbindEvents` methods from [Gmaps](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/gmaps.js) and create a mixin or a [high-order component](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750).
- [ ] add the `draggable` prop to [Marker](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/marker.js).

**Comment by MicheleBertoli** [comment]
Hey @gneutzling, I completed all the tasks in the [marker-events](https://github.com/MicheleBertoli/react-gmaps/tree/marker-events) branch.
Would you mind if I ask you to review/test the code?

**Comment by gneutzling** [comment]
Hey @MicheleBertoli, thanks and congrats.
I did some tests here and it is working pretty well.

I'll close this PR, because don't make sense anymore.

**Comment by MicheleBertoli** [comment]
Thanks @gneutzling, version 1.7 is out :)

**Pull request closed without merging**
