### PR TITLE
Update infoWindow.js

### PR DESCRIPTION
**Pull request by laurenskling**
Being able to set disableAutoPan and maxWidth in the InfoWindow via props would be really useful.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thanks @laurenskling for your contribution!

At this point, it would be nice to map all the [InfoWindowOptions](https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions), would you mind doing it?

I don't think we really need the ternary operator, you can just assign the prop directly like: 
```javascript
content: this.props.content
```

Have a nice day.

**Comment by MicheleBertoli** [comment]
Hey @laurenskling, working on #10 I changed a bit the way we set options for the InfoWindow component, see [here](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/infoWindow.js#L28).
It will be easier for you to add the new props ;)

**Comment by laurenskling** [comment]
Awesome work, thanks for replying so swiftly. I would be glad to extend these options!

**Comment by laurenskling** [comment]
Didn't really know how to update this pull request to the new version, so i made a new request:
https://github.com/MicheleBertoli/react-gmaps/pull/12

**Pull request closed without merging**
