### PR TITLE
Provide map instance and Maps API to callback

### PR DESCRIPTION
**Pull request by wmertens**
That way there's no need to fish with the ref.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thanks @wmertens but I can't see any real improvements on this PR.
Check out 1d5dfe0, you can now pass `styles` as a prop.

**Comment by wmertens** [comment]
Well, some of the things you can set on the Map object require creating an object and you need the lazily-loaded google.maps to create those.

If you pass the object and the API to the callback it can very simply use those, you can even use a single callback for multiple maps. The alternative example you gave requires keeping a ref and AFAIK the React team is considering changing the refs do be the DOM node directly.

It's not like this line of code will be a huge maintenance burden :)

**Comment by MicheleBertoli** [comment]
For multiple maps it's useful, I'll merge it.

The React team is going to change the refs to be DOM nodes just for DOM elements.
> Refs to custom component classes work exactly as before.

Thanks!

**Comment by wmertens** [comment]
:beers:

**Pull request merged**
