### PR TITLE
Add checks to see if the google lib has loaded

### PR DESCRIPTION
**Pull request by drKnoxy**
Ids are added to the global scope, so if you have `<div id="google" />` it will bipass this check

http://www.2ality.com/2012/08/ids-are-global.html
http://stackoverflow.com/questions/9228958/how-to-check-if-google-maps-api-is-loaded

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Oh, this is interesting. Thanks @drKnoxy 

Can you please fix the linting issue?

You could create a utility function (outside the object, line 3), like:
```javascript
const googleExists = () => (
  typeof window.google === 'object' && typeof window.google.maps === 'object'
);
```

And then use it like this:
```javascript
if (googleExists()) {
```

You also have to fix the tests (`google-maps-test.js`, line 27) adding the `maps` property to the fake object:
```javascript
window.google = { maps: {} };
```

**Comment by drKnoxy** [comment]
👍  pulled the repo down so i could use an ide and vscode, I guess github can't eslint and npm run scripts yet >_<

**Comment by MicheleBertoli** [comment]
Awesome, thanks @drKnoxy.
If you don't mind, I would ask you one more thing before merging: the indentation of line 52 should be 2 spaces for consistency (I'll add a `eslint` rule to enforce it).

**Comment by MicheleBertoli** [comment]
Thanks @drKnoxy 🙌

**Pull request merged**
